version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_alerts
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: alerts_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app

volumes:
  mongo_data:
